# Introduction

The Lanczos algorithm is a direct algorithm devised by Cornelius Lanczos that is an adaptation of power methods to find the $m$ "most useful" (tending towards extreme highest/lowest) eigenvalues and eigenvectors of an $n\times n$ Hermitian matrix, where $m$ is often but not necessarily much smaller than $n$.

The following is an implementation of the "classic" Lanczos algorithm.

# Import Dependencies

We begin by importing the necessary libraries.

In [1]:
import numpy as np 
from numpy import linalg as LA

# Lanczos Algorithm

Defined following the steps outlined in [https://en.wikipedia.org/wiki/Lanczos_algorithm](https://en.wikipedia.org/wiki/Lanczos_algorithm).

In [2]:
# Function to tri-diagonalize a matrix
def tridiag(a, b, c, k1=-1, k2=0, k3=1):
  return np.diag(a, k1) + np.diag(b, k2) + np.diag(c, k3)

# Lanczos algorithm
def lanczos(A, v1):
  np.set_printoptions(precision=3, suppress=True)
  # Step 1
  x, y = [], []
  n = A.shape[1]
  v2, beta = 0.0, 0.0

  for i in range(n):
    # Step 2
    w_prime = np.dot(A, v1)
    conj = np.matrix.conjugate(w_prime)
    alpha = np.dot(conj, v1)
    w = w_prime - alpha * v1 - beta * v2
    # Step 3
    beta = np.linalg.norm(w)
    # Step 4
    x.append(np.linalg.norm(alpha))

    # Reset
    if i < (n-1):
        y.append(beta)
    v2 = v1
    v1 = w/beta
    
  return tridiag(y, x, y)

# Example

We test our algorithm on an example where $A=\text{diag}\;(0,\;1,\;2,\;3,\;4,\;100000)$.

In [3]:
A = np.diag([0., 1., 2., 3., 4., 100000.])
n = A.shape[1]
v_0 = np.zeros(n)
v_0.fill(1.)
v = v_0/np.linalg.norm(v_0)

# Obtaining the tri-diagonal matrix T
T = lanczos(A, v)
print(T)

# Finding the eigenvalues w and eigenvectors v of the tri-diagonal matrix
w, v = LA.eig(T)
print(f'\n{w}')

[[16668.333 37267.054     0.        0.        0.        0.   ]
 [37267.054 83333.667     3.464     0.        0.        0.   ]
 [    0.        3.464     2.        1.183     0.        0.   ]
 [    0.        0.        1.183     2.        1.014     0.   ]
 [    0.        0.        0.        1.014    14.59   1121.957]
 [    0.        0.        0.        0.     1121.957 99987.365]]

[100000.         0.025      3.975      1.274      2.726  99999.955]
